package com.se.domain.configuration.event;

public enum EventType {
    ADD_TO_MY_PRODUCTS,
    SHARE_BY_EMAIL,
    REOPEN_AN_EXISTING_UID,
    OBSOLETE_POPUP,
    REOPEN_FILE,
    DUPLICATE,
    FEEDBACK,
    FORUM,
    LEGAL_DOC,
    SAMPLE,
    DOWNLOAD_CONFIGURATION,
    REOPEN_A_CONFIGURATION_URL,
    REOPEN_A_CONFIGURATION_TOOL,
    REOPEN_A_CUSTOMIZATION_URL,
    SEARCH_BY_REF
}
