name: ia-services-backend pr

on:
  push:
    branches-ignore:
      - develop
      - sqe
      - ppr
      - master

jobs:
  run-build-deploy:
    runs-on: orchestrator-runner
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3
        with:
          distribution: "temurin"
          java-version: 8
      - run: java -version
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.6.8
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Install python dependencies
        run: |
          pip3 install boto3 jinja2 pyyaml
          pip3 install awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LOWER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LOWER }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Quality Gate
        run: /bin/bash devops/qg/qg1.sh
        env:
          BRANCH_NAME: ${{ steps.build-context.outputs.branch_name }}
          REPOSITORY_NAME: ${{ steps.build-context.outputs.repository_name }}
